FROM burst/platformsh-php

ENV HOME /home/jenkins

# Replace shell with bash so we can source files etc.
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN addgroup --system --gid 10000 jenkins
RUN adduser --system --gid 10000 --home $HOME jenkins
LABEL Description="This is a base image, which provides the Jenkins agent executable (slave.jar)" Vendor="Jenkins project" Version="3.10"

ARG AGENT_WORKDIR=/home/jenkins/agent

RUN apt-get update && apt-get install -y && apt-get install apt-utils -y \
    && apt-get install curl bash git openssh-client openssl -y

USER root

ARG JENKINS_REMOTING_VERSION=3.12

# See https://github.com/jenkinsci/docker-slave/blob/2.62/Dockerfile#L32
RUN curl --create-dirs -sSLo /usr/share/jenkins/slave.jar https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/$JENKINS_REMOTING_VERSION/remoting-$JENKINS_REMOTING_VERSION.jar \
  && chmod 755 /usr/share/jenkins \
  && chmod 644 /usr/share/jenkins/slave.jar


RUN curl https://raw.githubusercontent.com/jenkinsci/docker-jnlp-slave/master/jenkins-slave --output /usr/local/bin/jenkins-slave

RUN cd /usr/local/bin/ && ls -la


RUN chmod a+rwx /home/jenkins
WORKDIR /home/jenkins


USER jenkins
ENV AGENT_WORKDIR=${AGENT_WORKDIR}
RUN mkdir /home/jenkins/.jenkins && mkdir -p ${AGENT_WORKDIR}

VOLUME /home/jenkins/.jenkins
VOLUME ${AGENT_WORKDIR}
WORKDIR /home/jenkins


ENTRYPOINT ["jenkins-slave"]
