FROM circleci/openjdk:jdk-stretch


RUN sudo apt-get update; sudo apt-get install -y -t openjdk-8-jre openjdk-8-jre-headless openjdk-8-jdk openjdk-8-jdk-headless

RUN sudo apt-get install curl -y && \
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && \
    sudo apt-get install build-essential nodejs -y

RUN sudo npm install gulp -g && npm link gulp

# start xvfb automatically to avoid needing to express in circle.yml
ENV DISPLAY :99
RUN printf '#!/bin/sh\nXvfb :99 -screen 0 1280x1024x24 &\nexec "$@"\n' > /tmp/entrypoint \
  && chmod +x /tmp/entrypoint \
        && sudo mv /tmp/entrypoint /docker-entrypoint.sh


# ensure that the build agent doesn't override the entrypoint
LABEL com.circleci.preserve-entrypoint=true

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/bin/sh"]
