version: 2
jobs:
  build:
    docker:
      - image: looztra/alpine-docker-client:latest
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: echo ${PWD}
      - run: ls -la
      - run: ./pushToHub.sh
