version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: ./pushToHub.sh
