version: 2
jobs:
  build:
    docker:
      - image: looztra/alpine-docker-client:latest
    steps:
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: echo ${PWD}
      - run: ls -la
      - run: echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/community" >> /etc/apk/repositories
      - run: echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
      - run: apk update
      - run: apk add --upgrade apk-tools@edge
      - run: apk add busybox
      - run: apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main --repository http://dl-cdn.alpinelinux.org/alpine/edge/community docker
      - run: service docker start
      - run: ./pushToHub.sh
